apiVersion: v1
kind: Pod
metadata: 
  name: grafana-pod
  labels:
    author: praveen
    type: grafana
spec:
  containers:
    - name: grafana-container
      image: registry.hub.docker.com/praveen88/personalimages:mygrafana_1.0
      ports:
        - containerPort: 3000
