apiVersion: v1
kind: Service
metadata:
  name: prometheusservice
spec:
    type: NodePort
    ports:
     - targetPort: 9090
       port: 9090
       NodePort: 30008
  selector:
     type: prometheus
